[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
build = "build.rs"
name = "svd_board"
version = "0.1.0"

[build-dependencies]
svd-parser = "0.1.1"
inflections = "1.0.0"
svd_codegen = "0.1.1"

[dependencies]
once = "0.3.2"
volatile = "0.2.0"

[lib]

[features]
stm32f7 = []
